name: CI
on: [push]
jobs:
 
  dusk-php:
    runs-on: ubuntu-latest
    env:
      APP_URL: "http://127.0.0.1:8000"
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: log
      TEST_VAR1: Testing 123
    steps:
      - uses: actions/checkout@v3
      - name: Prepare The Environment
        run: cp .env.example .env
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE \`dusk\` character set UTF8mb4 collate utf8mb4_bin;"
      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect
      - name: Ensure the ChromeDriver binaries are executable
        run: sudo chmod -R 0755 ./vendor/laravel/dusk/bin/
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &
      - name: Run Laravel Server
        run: php artisan serve --no-reload &
      - name: Check Chrome version
        run: /usr/bin/chromium-browser --version
      - name: Clear cache
        run: php artisan config:clear
      - name: Check Chrome version again
        run: /usr/bin/chromium-browser --version
      - name: Test env var
        run: echo "${{ env.TEST_VAR1 }} ${{ vars.TEST_VAR }}"
      - name: Run Dusk Tests
        run: sudo php artisan dusk:chrome --filter LoginTest 
      - name: Check file exists
        run: test -e ./tests/Browser/source/Src_001.txt && echo file exists || echo file not found
      - name: Page source
        run: cat ./tests/Browser/source/Src_001.txt
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console
          
      - name: Laravel PHPUnit
        # You may pin to the exact commit or the version.
        # uses: nathanheffley/laravel-phpunit-action@1ac680fbc5f20621343f0d7ba450a02b807c576e
        uses: nathanheffley/laravel-phpunit-action@v0.1.0
  
  job2:
    runs-on: ubuntu-latest
    needs: dusk-php
    steps:
      - name: Helo
        run: echo aloha
